#right shift
a=int(input())
print('right shift values')
print('right shift 1',a>>1)
print('right shift 2',a>>2)
print('right shift 3',a>>3)
print('right shift 4',a>>4)
print('right shift 5',a>>5)
print('right shift 6',a>>6)
print('right shift 7',a>>7)
print('right shift 8',a>>8)
print('right shift 9',a>>9)
